
################################################################
# Metadata
################################################################

# Basics
title:              ethericbod.pw, 2016
email:
author:
  name:             'Natasha Habedus'
description:        ''
url:                'http://nhabedus.github.io/project1/'
baseurl:            ''


################################################################
# Configuration
################################################################

# Setup
destination:        ./_site

markdown:           redcarpet
highlighter:        rouge
sass:
  sass_dir:         _sass
  style:            compressed
exclude:            [Gemfile, Gemfile.lock] #, README.md]
include:            [.gitignore, .nojekyll]

# Page Structure
relative_permalinks: true

# Google Analytics
analytics:
  active:           'false'
  userID:           ''
